name: Build Kernel

on:
  workflow_dispatch:
     branches:
     - openela-base-357-ksun_legacy

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set timezone
        run: |
          sudo timedatectl set-timezone Asia/Dhaka

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc git-core python2 gnupg flex bison build-essential \
            zip curl wget zlib1g-dev libc6-dev-i386 \
            libncurses5 lib32ncurses5-dev x11proto-core-dev \
            libx11-dev lib32z1-dev libgl1-mesa-dev \
            libxml2-utils xsltproc unzip fontconfig \
            libssl-dev ccache cpio

      - name: Make script executable
        run: |
          chmod +x build.sh
          sed -i 's/\r$//' build.sh

      - name: Build Kernel
        run: |
          ./build.sh ksu

      - name: Find ZIP
        id: zip
        run: |
          ZIP=$(find . -maxdepth 1 -name "*.zip" | head -n 1)
          echo "zip=$ZIP" >> $GITHUB_OUTPUT

      - name: Generate Tag
        id: tag
        run: |
          echo "tag=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Kernel Build ${{ steps.tag.outputs.tag }}
          files: |
            ${{ steps.zip.outputs.zip }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
